[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CoolPDLP = "9e90bdc5-3073-4e0f-a275-e19f28ac1b53"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
