name = "CoolPDLP"
uuid = "9e90bdc5-3073-4e0f-a275-e19f28ac1b53"
version = "0.1.0"
authors = ["Guillaume Dalle"]

[workspace]
projects = ["docs", "test"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[weakdeps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[extensions]
CoolPDLPMOIExt = "MathOptInterface"

[compat]
Adapt = "4.4.0"
Atomix = "1.1.2"
DispatchDoctor = "0.4.26"
DocStringExtensions = "0.9.5"
IterativeSolvers = "0.9.4"
KernelAbstractions = "0.9.38"
LinearAlgebra = "1"
MathOptInterface = "1"
Printf = "1.11.0"
ProgressMeter = "1.11.0"
QPSReader = "0.2.1"
Random = "1.11.0"
SparseArrays = "1"
StableRNGs = "1.0.3"
julia = "1.11"
