name = "CoolPDLP"
uuid = "9e90bdc5-3073-4e0f-a275-e19f28ac1b53"
version = "0.1.0"
authors = ["Guillaume Dalle"]

[workspace]
projects = ["docs", "test", "benchmark", "challenge"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Accessors = "0.1.42"
Adapt = "4.4.0"
Atomix = "1.1.2"
DataDeps = "0.7.13"
DispatchDoctor = "0.4.26"
DocStringExtensions = "0.9.5"
GPUArrays = "11.2.6"
GZip = "0.6.2"
IterativeSolvers = "0.9.4"
KernelAbstractions = "0.9.38"
LinearAlgebra = "1"
Logging = "1.11.0"
OhMyThreads = "0.8.3"
ProgressMeter = "1.11.0"
QPSReader = "0.2.1"
Random = "1.11.0"
SparseArrays = "1"
StableRNGs = "1.0.3"
Statistics = "1.11.1"
julia = "1.10"
