[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CoolPDLP = "9e90bdc5-3073-4e0f-a275-e19f28ac1b53"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
