[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CoolPDLP = "9e90bdc5-3073-4e0f-a275-e19f28ac1b53"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
